const blogs = [
  {
    id: '0',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '1',
    label: 'travel0',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '2',
    label: 'travel1',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '3',
    label: 'travel2',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '4',
    label: 'travel3',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '5',
    label: 'travel5',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '6',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '7',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '8',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '9',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '10',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '11',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '12',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '13',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '14',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '15',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '16',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '17',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '18',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '19',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '20',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '21',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '22',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '23',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
  {
    id: '24',
    label: 'travel',
    title: 'Set Video Playback Speed With Javascript',
    profilePic: 'img/author.png',
    name: 'Jennie Kiaa',
    date: '07 December 2022',
    timeToRead: 3,
    content: `Did you come here for something in particular or just general Riker-bashing?
        And blowing into`,
  },
];

const authors = [
  {
    name: 'Jeni Kia',
    job: 'Fashion designer, Blogger, activist',
    fb: 'https://www.facebook.com',
    twit: 'https://www.twitter.com',
    insta: 'https://www.instagram.com',
    profilePic: '/img/jeni-kia.jpg',
    totalPosts: 6,
    aboutAuthor: 'Curabitur ultrices mi risus, et molestie augue ultrices eu. In sed purus tellus. Integer rutrum ex enim, vitae tincidunt sem dictum quis. In velit tellus, bibendum a mi et, pharetra laoreet arcu. Suspendisse potenti. Aenean leo ligula, aliquet id magna ac, eleifend aliquam nulla. Proin dignissim, quam ut vulputate cursus, arcu nunc rhoncus nisi, vel rutrum sem magna eu lectus. Suspendisse eu nunc neque. Morbi at metus interdum erat bibendum bibendum et a elit. Nulla non magna ac mi accumsan mollis. Morbi posuere erat at enim tempor, ut varius lorem sagittis.',
    authorQuote: 'Go ahead, make my day.',
    quoteDesc: 'Nullam odio enim, vulputate sed ultrices vitae, egestas eu urna. Nulla sagittis cursus tortor, id ornare ex congue sit amet. Phasellus blandit vel augue sit amet placerat. Donec non porttitor tellus, vitae porttitor ex. Cras laoreet faucibus pretium.',
  },
  {
    name: 'Andress Rasle',
    job: 'Blogger, activist, content creator, part time designer at: www.gethugothemes.com',
    fb: 'https://www.facebook.com',
    twit: 'https://www.twitter.com',
    insta: 'https://www.instagram.com',
    profilePic: '/img/andress-rasle.jpg',
    totalPosts: 12,
    aboutAuthor: 'Suspendisse porta iaculis augue in sodales. Nam vitae nulla non massa hendrerit bibendum. Mauris magna quam, varius eget enim non, bibendum luctus velit. Suspendisse a accumsan nibh. Etiam orci est, ornare mollis porttitor non, maximus non ex. In posuere leo quis tellus vulputate tempor. Quisque nec finibus ante. ',
    authorQuote: 'For those to whom much is given, much is required.',
    quoteDesc: ' Sed maximus ipsum felis, vel luctus lorem dictum ut. Fusce quis luctus purus. Suspendisse condimentum malesuada elit nec scelerisque.',
  },
  {
    name: 'Maria Jenin',
    job: 'Fashion designer, Blogger, activist',
    fb: 'https://www.facebook.com',
    twit: 'https://www.twitter.com',
    insta: 'https://www.instagram.com',
    profilePic: '/img/maria-jenin.jpg',
    totalPosts: 8,
    aboutAuthor: ' Morbi dictum pellentesque arcu, a cursus sapien tempus nec. Vestibulum magna ligula, ornare cursus dignissim eget, fermentum a justo.In dolor erat, tincidunt sit amet dui vitae, rutrum ultricies elit. Cras et pharetra nunc, sed dapibus ante. Aliquam felis lectus, placerat a molestie sit amet, gravida vitae eros. Duis fringilla aliquam eros et imperdiet. Aliquam interdum volutpat libero id imperdiet. Nulla vel felis non sem maximus ornare sed sed nibh. Donec iaculis malesuada felis sed faucibus',
    authorQuote: 'Here\'s looking at you, kid.',
    quoteDesc: 'Quisque mattis massa ut eleifend tempor. Sed pellentesque, elit ac commodo fermentum, urna dui faucibus erat, ac hendrerit massa dui id lectus. Quisque sed enim quis sapien scelerisque ullamcorper ut ut mi. ',
  },
  {
    name: 'simon D’silva',
    job: 'Fashion designer, Blogger, activist',
    fb: 'https://www.facebook.com',
    twit: 'https://www.twitter.com',
    insta: 'https://www.instagram.com',
    profilePic: '/img/simon-dsilva.jpg',
    totalPosts: 6,
    aboutAuthor: 'Praesent sapien libero, fermentum vitae orci at, congue volutpat lorem. Suspendisse potenti. Pellentesque rutrum, mi mattis gravida rutrum, ligula dolor sollicitudin lorem, id tincidunt ante mi vitae magna. Duis eleifend ligula ac lorem volutpat luctus. ',
    authorQuote: 'I think therefore I am.',
    quoteDesc: 'Quisque velit nibh, sagittis quis nibh vitae, interdum interdum sem. Ut a gravida urna',
  },
  {
    name: 'enna lee',
    job: 'Blogger, activist, content creator, part time designer at: www.gethugothemes.com',
    fb: 'https://www.facebook.com',
    twit: 'https://www.twitter.com',
    insta: 'https://www.instagram.com',
    profilePic: '/img/enna-lee.jpg',
    totalPosts: 10,
    aboutAuthor: 'Ut pretium sem at nisl scelerisque, non posuere enim eleifend. Vestibulum ac lectus lacinia, maximus lorem a, ultrices dui. Cras arcu mi, ultricies vel velit quis, aliquam mollis nisi. Sed tempor vel mauris id auctor. Cras porta at dolor ullamcorper rhoncus. Vivamus dignissim purus vel ante ornare sodales. ',
    authorQuote: 'I love the smell of napalm in the morning.',
    quoteDesc: 'Integer enim turpis, vestibulum quis sodales eu, tempus nec ex. Vivamus mollis molestie ipsum sed bibendum. Proin arcu massa, commodo nec condimentum ac, ultricies eget urna.',
  },
  {
    name: 'asa agarwal',
    job: 'Fashion designer, Blogger, activist',
    fb: 'https://www.facebook.com',
    twit: 'https://www.twitter.com',
    insta: 'https://www.instagram.com',
    profilePic: '/img/asa-agarwal.jpg',
    totalPosts: 4,
    aboutAuthor: 'auris ornare lobortis urna vitae fringilla. Maecenas vitae posuere dolor. Curabitur at blandit metus. Phasellus aliquam, augue nec semper imperdiet, magna metus vulputate dolor, ac suscipit augue felis id lorem. Proin et ante a ante ultrices blandit id at arcu. Aliquam vel ligula a lacus facilisis feugiat non vitae erat. Maecenas sempe',
    authorQuote: 'I\'ll be back.',
    quoteDesc: 'eros congue posuere egestas, mauris enim vestibulum turpis, et malesuada sem tortor ac justo. Aenean et massa turpis.',
  },
];

const featuredCompanies = ['img/grammarly.png', 'img/medium.png', 'img/unsplash.png', 'img/wordpress.png', 'img/blogger.png', 'img/medium.png', 'img/grammarly.png', 'img/wordpress.png', 'img/unsplash.png', 'img/grammarly.png'];
export { authors, featuredCompanies };
export default blogs;
